<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SystemTrayProcessManager.Core</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
